spring:
  # 데이터 소스 설정
  datasource:
    url: jdbc:mariadb://localhost:3306/myblog
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
    data: classpath:data.sql
    initialization-mode: always

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

